// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC1a3iZEYEeFeQgiGSFC6QZnGLjY5WLEs',
    appId: '1:945511347242:web:d2f9e3909114ac8fb23f53',
    messagingSenderId: '945511347242',
    projectId: 'mamba-fast',
    authDomain: 'mamba-fast.firebaseapp.com',
    storageBucket: 'mamba-fast.firebasestorage.app',
    measurementId: 'G-RJ421G9TL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNqfSszqEQ2RFZbjCwvohBQW7KSYbITes',
    appId: '1:945511347242:android:ab8809371328c459b23f53',
    messagingSenderId: '945511347242',
    projectId: 'mamba-fast',
    storageBucket: 'mamba-fast.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeGrPPedohbo86NtLfqnl9KJvTQH7Rh8',
    appId: '1:945511347242:ios:762469bb26d7be93b23f53',
    messagingSenderId: '945511347242',
    projectId: 'mamba-fast',
    storageBucket: 'mamba-fast.firebasestorage.app',
    iosBundleId: 'com.example.mambaFastTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLeGrPPedohbo86NtLfqnl9KJvTQH7Rh8',
    appId: '1:945511347242:ios:762469bb26d7be93b23f53',
    messagingSenderId: '945511347242',
    projectId: 'mamba-fast',
    storageBucket: 'mamba-fast.firebasestorage.app',
    iosBundleId: 'com.example.mambaFastTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC1a3iZEYEeFeQgiGSFC6QZnGLjY5WLEs',
    appId: '1:945511347242:web:7760692fb7c4ed0bb23f53',
    messagingSenderId: '945511347242',
    projectId: 'mamba-fast',
    authDomain: 'mamba-fast.firebaseapp.com',
    storageBucket: 'mamba-fast.firebasestorage.app',
    measurementId: 'G-VFGJCJL48R',
  );
}
